code: test-book
title: Test Book
toc:
  - code: about
    title: About
    id: 30700ff3-f211-479a-8e71-7a86bf60288d
    topics:
      - code: book
        title: Book
        id: ecda8b51-11d5-49fd-ac94-fc89d73ebb84
      - code: Hello
        title: Hello
        id: fde1b46e-1204-4948-b46e-edb55172ff4a
      - code: hi
        title: Hi
        id: f19c9d38-0ad0-4cb6-b650-52e4da884cc9
      - code: hi-1
        title: Hi
        id: 41d74e11-02fb-49d5-966c-37a59a22aecf
